# SPDX-License-Identifier: LGPL-2.1-or-later
#
# SPDX-FileCopyrightText: 2020 CERN

include:
  - project: 'be-cem-edl/evergreen/gitlab-ci'
    ref: master
    file:
      - 'edl-gitlab-ci.yml'

variables:
  EDL_CI_DOC_SRC_PATH: 'doc'
  EDL_CI_DOC_DST_PATH: '$EDL_CI_EOS_OUTPUT_DIR/doc'

cppcheck:
  stage: analyse
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/static-analysis:latest
  script:
    - make -C software cppcheck

.script_fetch_kernel_dep: &script_fetch_kernel_dep
  - git clone --depth 1 https://gitlab.cern.ch/fvaga/fpga-manager.git ~/git/fpga-mgr
  - export FPGA_MGR=~/git/fpga-mgr
  - git clone -b v1.1.5 --depth 1 https://ohwr.org/project/fmc-sw.git ~/git/fmc
  - export FMC=~/git/fmc
  - git clone --depth 1 https://ohwr.org/project/general-cores.git ~/git/general-cores/
  - export SPI=~/git/general-cores/software/spi-ocores
  - export I2C=~/git/general-cores/software/i2c-ocores

.script_build_kernel_dep: &script_build_kernel_dep
  - make -C $FPGA_MGR all
  - make -C $FMC/drivers/fmc all

build-centos-7:
  stage: build
  variables:
    CONFIG_FPGA_MGR_BACKPORT: y
    KERNELSRC: /usr/src/kernels/*/
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/build-centos-7:latest
  before_script:
    - *script_fetch_kernel_dep
    - *script_build_kernel_dep
  script:
    - make -C software

kernel_build_validation:
  extends: .kernel_build_validation
  before_script:
    - export CONFIG_FPGA_MGR_BACKPORT=n
    - *script_fetch_kernel_dep
    - *script_build_kernel_dep
