# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: 2020 CERN

stages:
  - static-analysis
  - build
  - dkms

reuse:
  stage: static-analysis
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
  allow_failure: true

cppcheck:
  stage: static-analysis
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/static-analysis:latest
  script:
    - make -C software cppcheck

documentation:
  stage: build
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/documentation:latest
  script:
    - make -C doc html
  allow_failure: true

.script_fetch_kernel_dep: &script_fetch_kernel_dep
  - git clone --depth 1 https://gitlab.cern.ch/fvaga/fpga-manager.git ~/git/fpga-mgr
  - export FPGA_MGR=~/git/fpga-mgr
  - export CONFIG_FPGA_MGR_BACKPORT=y
  - git clone --depth 1 https://gitlab.cern.ch/coht/fmc.git ~/git/fmc
  - export FMC=~/git/fmc
  - git clone --depth 1 https://ohwr.org/project/general-cores.git ~/git/general-cores/
  - export SPI=~/git/general-cores/software/spi-ocores
  - export I2C=~/git/general-cores/software/i2c-ocores

.script_build_kernel_dep: &script_build_kernel_dep
  - make -C $FPGA_MGR all
  - make -C $FMC/drivers/fmc all

build-centos-7:
  stage: build
  variables:
    LINUX: /usr/src/kernels/*/
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/build-centos-7:latest
  before_script:
    - *script_fetch_kernel_dep
    - *script_build_kernel_dep
  script:
    - make -C software

.script_build_kernel_ver: &script_build_kernel_ver
  - source /linux-versions.sh
  - fetch $VERSION && prepare $VERSION && export LINUX=$(linux $VERSION)
  - *script_build_kernel_dep
  - make -C software/kernel all

build-kernel-5.4.129:
  stage: build
  allow_failure: true
  variables:
    VERSION: 5.4.129
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/build-kernel:latest
  before_script:
    - *script_fetch_kernel_dep
  script:
    - *script_build_kernel_ver

build-kernel-5.10.47:
  stage: build
  allow_failure: true
  variables:
    VERSION: 5.10.47
  image:
    name: gitlab-registry.cern.ch/coht/common-containers/build-kernel:latest
  before_script:
    - *script_fetch_kernel_dep
  script:
    - *script_build_kernel_ver
