---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

# The version of the .ohwr.yaml template.
version: '1.0.0'

project:

  # The name of your project.
  name: 'Simple PCIe FMC carrier (SPEC)'

  # The description of your project.
  description: 'https://raw.githubusercontent.com/wiki/vascoguita/spec/Home.md'

  # The website of your project.
  # Use the web page of your git repository if your project doesn't have dedicated website
  # (e.g. 'https://github.com/user/project').
  website: 'https://ohwr.org/project/spec'

  # The licenses of your project. Use SPDX identifiers - https://spdx.org/licenses/.
  licenses:
    - 'CC-BY-SA-4.0'
    - 'CERN-OHL-W-2.0'
    - 'GPL-2.0-or-later'
    - 'LGPL-2.1-or-later'

  # (optional) Images of your project (e.g. a photo of the latest prototype).
  images:
    - 'https://ohwr.org/project/spec/uploads/3b5326fd6ed2dc55b2e26e8c25f826fd/spec_v4_top.jpg'
    - 'https://ohwr.org/project/spec/uploads/b9ea47be8f4a6a411dd444e432868bd7/spec.JPG'
    - 'https://ohwr.org/project/spec/uploads/1da041f7ed1da9b42d1b83f77528a11d/spec_v2.jpg'
    - 'https://ohwr.org/project/spec/uploads/036da7721683445ec3e5d5d0a8a855c8/SPEC_top_high_res.jpg'
    - 'https://ohwr.org/project/spec/uploads/0e72fd9272d29cd6e0e67de39924cb78/SPEC_bottom_high_res.jpg'

  # (optional) Link to the documentation of your project.
  documentation: 'https://ohwr.org/project/spec/wikis'

  # (optional) Link to the issue/bug tracker of your project.
  issues: 'https://ohwr.org/project/spec/issues'

  # (optional) Link to the latest release of your project.
  latest_release: 'https://ohwr.org/project/spec/tags/v3.0.0'
  
  # (optional) News feed of your project.
  news:
    - title: 'SPEC gateware/software v2.0.2 released'
      date: 2020-09-29
    - title: 'SPEC gateware/software v2.0.0 released'
      date: 2020-07-30
    - title: 'Created documentation for SPEC150 that has a larger FPGA'
      date: 2019-12-19
    - title: 'Over 2000 SPEC boards produced by industry'
      date: 2018-12-19
      content: |
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
        Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. 
    - title: 'Start of study of a new design. Contact Erik van der Bij - CERN'
      date: 2018-01-11

  # (optional) Link to the forum where your community has conversations, asks questions and posts answers.
  forum: 'https://forums.ohwr.org/c/spec'
  links:
    - name: 'Getting Started with the SPEC documentation'
      url: 'https://www.ohwr.org/project/white-rabbit/uploads/e747a4d84a62dcb0f9d784621137b003/spec-getting-started-v1.0-201403.pdf'
    - name: 'SPEC - INCAA Computers, Netherlands'
      url: 'https://www.incaacomputers.com/products/by-standard/fmc/spec/'
    - name: 'FAQ'
      url: 'https://ohwr.org/project/spec/wikis/FAQ'
